import localFont from "next/font/local";
import "./globals.css";
import { Cormorant_Infant} from "next/font/google"; 
import NavBar from "./components/NavBar/page";
import Footer from "./components/Footer/page";


const headingFont = Cormorant_Infant({
    subsets:["latin"],
    weight:["400", "600", "700"],
    variable: "--heading-font",
});



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Tour App",
  description: "Generated by Tour app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-300`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
